name: Deploy Acs API

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build with Maven
        run: mvn package
        env:
          DATABASE_URL: ${{  secrets.DATABASE_URL }}
          DATABASE_USER: ${{  secrets.DATABASE_USER }}
          DATABASE_PASSWORD: ${{  secrets.DATABASE_PASSWORD }}

      - name: Login Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }}  -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run : docker build -t gabrielrtlima/sistema-acs .
      - name: Push image docker
        run: docker push gabrielrtlima/sistema-acs

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull gabrielrtlima/sistema-acs:latest
      - name: Run docker container
        run: sudo docker run -d -p 8080:8080 --name sistema-acs gabrielrtlima/sistema-acs
